url: https://datart-com-tr.github.io
baseurl: /

# Site settings
title: Datart
email: datart@datart.com.tr
description: "No nonsense. Data driven."


# Team names, titles and social links
people:
- name: Erhun Kundakcıoğlu
  pic: 1
  position: Director
  social:
    - title: linkedin
      url: # https://www.linkedin.com/in/erhunkundakcioglu
    - title: google-scholar
      url: # https://scholar.google.com/citations?user=k6NTKvsAAAAJ&hl=en
    - title: website
      url: # http://erhun.me

- name: Esad Simitcioğlu
  pic: 2
  position: Developer
  social:
    - title: linkedin
      url: #

- name: Ulvi Fındık
  pic: 3
  position: Scientist
  social:
    - title: linkedin
      url: #

- name: Elif Kardaş
  pic: 3
  position: Intern
  social:
    - title: linkedin
      url: #
      
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Balat Mah. Pamuklu sok.
  - line: Concept Balat No: 3/B24 Nilüfer BURSA

# Build settings
markdown: kramdown
permalink: pretty