#-------------------------------
# Site Settings
title: Datart Lab
logo: /images/logo_trimmed.png # You can add own logo. For example '/images/logo.png'.
description: Datart İleri Araştırma ve Geliştirme Laboratuvarı
color_scheme: light # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Çalışmalarımız'
      url: '/calismalarimiz/'
    - title: 'Ekibimiz'
      url: '/ekibimiz/'
    - title: 'İletişim'
      url: '/iletisim/'


#-------------------------------
# Author Settings
author:
  author__name:
  author__bio:
  author__avatar:

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title:
  hero__description:
  hero__image: /images/hero.jpg


#-------------------------------
# Logos Settings
logos:
  enable: true
  logos__title: Endüstri Ortaklarımız

logo__items:

  - name: Arute
    link: "https://arutesolutions.com/"
    image: "/images/arute.png"

  - name: ATV
    link: "https://www.atv.com.tr"
    image: "/images/atv.png"

  - name: Bicakcilar
    link: "https://kocmedical.com/"
    image: "/images/bicakcilar.svg"

  - name: Borcelik
    link: "https://www.borcelik.com/"
    image: "/images/borcelik.png"

  - name: Cansan
    link: "https://www.cansan.com.tr/"
    image: "/images/cansan.png"

  - name: Durak
    link: "https://durak.com/"
    image: "/images/durak.png"

  - name: Funthemental
    link: "http://www.funthemental.com.tr/"
    image: "/images/fm.png"

  - name: Harris Health
    link: "https://www.harrishealth.org/"
    image: "/images/hh.png"

  - name: Hitit
    link: "https://www.hitit.com/"
    image: "/images/hitit.png"

  - name: Honeywell
    link: "https://www.honeywell.com/"
    image: "/images/hw.png"

  - name: Keller Williams
    link: "https://www.kw.com/"
    image: "/images/kw.png"

  - name: Kronos
    link: "https://www.ukg.com/"
    image: "/images/ukg.png"

  - name: Magic Generations
    link: "https://www.mgsportif.com/"
    image: "/images/mg.png"

  - name: Mir Unique Solutions
    link: "https://www.mirarge.com/"
    image: "/images/mir.png"

  - name: Modular Mining
    link: "https://www.komatsu.com/"
    image: "/images/Komatsu.png"

  - name: Odysee
    link: "https://www.odysee.ai/"
    image: "/images/odysee.png"

  - name: Tam Finans
    link: "https://www.tamfinans.com.tr/"
    image: "/images/tamfinans.png"


#-------------------------------
# Newsletter
mailchimp:
  enable: false
  mailchimp__identifier:
  mailchimp__input__text:
  mailchimp__button__text:


#-------------------------------
# Work Settings
calismalarimiz:
  enable: true
  work__title: Öne Çıkan Projeler
  

#-------------------------------
# Publications Settings
publications:
  enable: true
  publications__title: Yayınlar
  publications__description:

  publications__items:
    - citation: "U. Findik, O. E. Kundakcioglu, and S. Alizamir. <em>Handbook of Combinatorial Optimization</em>, 3rd Ed., P. M. Pardalos and O. A. Prokopyev, Eds., Springer, 2024, ch. Generalized assignment problem."
      paper_url: "https://link.springer.com/rwe/10.1007/978-3-030-54621-2_200-2"
    - citation: "C. Y. Yildiz and O. E. Kundakcioglu. Disaster relief inventory simulation: Managing resources in humanitarian camps. <em>Proceedings of the 2024 INFORMS Winter Simulation Conference</em>."
      paper_url: "https://ieeexplore.ieee.org/document/10838763"
    - citation: "S. Azizi, D. N. Yoltay, and O. E. Kundakcioglu. <em>Handbook of Combinatorial Optimization</em>, 3rd Ed., P. M. Pardalos and O. A. Prokopyev, Eds., Springer, 2024, ch. Inventory management for medical supplies."
      paper_url: "https://link.springer.com/rwe/10.1007/978-3-030-54621-2_877-1"
    - citation: "C. Y. Yildiz and O. E. Kundakcioglu. <em>Handbook of Combinatorial Optimization</em>, 3rd Ed., P. M. Pardalos and O. A. Prokopyev, Eds., Springer, 2024, ch. Optimization for time series decomposition."
      paper_url: "https://link.springer.com/rwe/10.1007/978-3-030-54621-2_881-1"  
    - citation: "H. Shourabizadeh, O. E. Kundakcioglu, C. D. C. Bozkir, M. B. Tufekci, and A. C. Henry. <em>Healthcare Inventory Management in the Presence of Supply Disruptions and a Reliable Secondary Supplier</em>. <em>Annals of Operations Research</em>, 2023, vol. 331, pp. 1149-1206."
      paper_url: "https://doi.org/10.1007/s10479-023-05620-y"

    - citation: "I. E. Sakarya and O. E. Kundakcioglu. Multi-instance learning by maximizing the area under receiver operating characteristic curve. <em>Journal of Global Optimization</em>, 2023, vol. 85, pp. 351-375."
      paper_url: "https://doi.org/10.1007/s10898-022-01219-y"
      github_url: "https://github.com/OEKundakcioglu/MI-ROCMax"

    - citation: "C. D. C. Bozkir, O. E. Kundakcioglu, and A. C. Henry. Hospital service levels during drug shortages: Stocking and transshipment policies for pharmaceutical inventory. <em>Journal of Global Optimization</em>, 2022, vol. 83, pp. 565-584."
      paper_url: "https://doi.org/10.1007/s10898-021-01058-3"
      github_url: "https://github.com/OEKundakcioglu/HospitalInventorySimulation"

    - citation: "S. Korkmaz, O. E. Kundakcioglu, and O. Sivrikaya. A fluid approximation for the single-leg fare allocation problem with nonhomogeneous Poisson demand. <em>Journal of Revenue and Pricing Management</em>, 2022, vol. 21, pp. 81-96."
      paper_url: "https://doi.org/10.1057/s41272-021-00284-4"

    - citation: "O. Simsek and O. E. Kundakcioglu. Cost of fairness in agent scheduling for contact centers. <em>Journal of Industrial and Management Optimization</em>, 2022, vol. 18, no. 2, pp. 873-896."
      paper_url: "https://doi.org/10.3934/jimo.2021001"

    - citation: "S. Azizi, C. D. C. Bozkir, A. C. Trapp, O. E. Kundakcioglu, and A. K. Kurbanzade. Aid allocation for camp-based and urban refugees with uncertain demand and replenishments. <em>Production and Operations Management</em>, 2021, vol. 30, no. 12, pp. 4455-4474."
      paper_url: "https://doi.org/10.1111/poms.13531"
      github_url: "https://github.com/OEKundakcioglu/RefugeeAidAllocation"

    - citation: "S. Gozuyilmaz and O. E. Kundakcioglu. Mathematical optimization for time series decomposition. <em>OR Spectrum</em>, 2021, vol. 43, pp. 733-758."
      paper_url: "https://doi.org/10.1007/s00291-021-00637-w"

    - citation: "M. Önal, O. E. Kundakcioglu, and S. Jain. An EOQ model with deteriorating items and self-selection constraints. <em>Optimization Letters</em>, 2020, vol. 14, pp. 1491-1518."
      paper_url: "https://doi.org/10.1007/s11590-020-01566-3"

    - citation: "T. Yavuz, O. E. Kundakcioglu, and T. Ünlüyurt. Exact and heuristic approaches to detect failures in failed k-out-of-n systems. <em>Computers and Operations Research</em>, 2019, vol. 112, 104752."
      paper_url: "https://doi.org/10.1016/j.cor.2019.07.010"

    - citation: "N. R. Barshes, S. Saedi, J. Wrobel, P. Kougias, O. E. Kundakcioglu, and D. G. Armstrong. A model to estimate cost-savings in diabetic foot ulcer prevention efforts. <em>Journal of Diabetes and Its Complications</em>, 2017, vol. 31, no. 4, pp. 700-707."
      paper_url: "https://doi.org/10.1016/j.jdiacomp.2016.12.017"

    - citation: "B. Balcik, C. D. C. Bozkir, and O. E. Kundakcioglu. A literature review on inventory management in humanitarian supply chains. <em>Surveys in Operations Research and Management Science</em>, 2016, vol. 21, no. 2, pp. 101-116."
      paper_url: "https://doi.org/10.1016/j.sorms.2016.10.002"

    - citation: "M. Önal, A. Yenipazarli, and O. E. Kundakcioglu. A mathematical model for perishable products with price- and stock-dependent demand. <em>Computers and Industrial Engineering</em>, 2016, vol. 102, pp. 246-258."
      paper_url: "https://doi.org/10.1016/j.cie.2016.11.002"

    - citation: "S. Saedi, O. E. Kundakcioglu, and A. C. Henry. Mitigating the impact of drug shortages for a healthcare facility: An inventory management approach. <em>European Journal of Operational Research</em>, 2016, vol. 251, no. 1, pp. 107-123."
      paper_url: "https://doi.org/10.1016/j.ejor.2015.11.017"

    - citation: "H. Yang, O. E. Kundakcioglu, and D. Zeng. Healthcare data analytics. <em>Information Systems and e-Business Management</em>, 2015, vol. 13, no. 4, pp. 595-597."
      paper_url: "https://link.springer.com/article/10.1007/s10257-015-0297-0"
    - citation: "M. H. Poursaeidi and O. E. Kundakcioglu. Robust support vector machines for multiple instance classification. <em>Annals of Operations Research</em>, 2014, vol. 216, no. 1, pp. 205-227."
      paper_url: "https://doi.org/10.1007/s10479-012-1241-z"

    - citation: "H. Yang and O. E. Kundakcioglu. Healthcare intelligence: Turning data into knowledge. <em>IEEE Intelligent Systems, Trends & Controversies</em>, 2014, vol. 29, no. 3, pp. 54-56."
      paper_url: "https://ieeexplore.ieee.org/document/6871721"
    - citation: "S. Saedi and O. E. Kundakcioglu. <em>Handbook of Combinatorial Optimization</em>, 2nd Ed., P. M. Pardalos, D.-Z. Du, and R. Graham, Eds., Springer, 2013, ch. Combinatorial optimization in data mining, pp. 595-630."
      paper_url: "https://link.springer.com/referencework/10.1007/978-1-4419-7997-1"
    - citation: "M. H. Poursaeidi, M. Samorani, and O. E. Kundakcioglu. Offshore wind farm layout optimization: What is the hype? <em>Proceedings of the Industrial and Systems Engineering Research Conference</em>, ID: 952, 2013."


#-------------------------------
# Testimonials Section
testimonials:
  enable: true

testimonial__title:
testimonial__description:

testimonial__items:

  - name: "Ahmet Mert Yazıcı"
    image: "/images/mert-yazici.jpg"
    designation:
    link:
    content: >
      Mert, Datart Laboratuvarı'nda ölçeklenebilir uygulamalar, backend servisleri, veri odaklı çözümler ve kullanıcıya yönelik platformların tasarımı ve geliştirilmesine odaklanmaktadır. 
      Şu anda [Koç Üniversitesi](http://ku.edu.tr/)'nde Bilgisayar Mühendisliği okurken İşletme çift anadal yapmaktadır.
    socials:
      - { icon: "ion ion-logo-linkedin", link: "https://www.linkedin.com/in/ahmet-mert-yazici" }
      - { icon: "ion ion-logo-github", link: "https://github.com/ayazici21" }
    hobbies:
      - { icon: "☕", label: "Espresso" }
      - { icon: "🎬", label: "Interstellar" }
      - { icon: "🎮", label: "Resident Evil" }
      - { icon: "🎵", label: "Progressive Metal" }
    hobby_icons:
      - { icon: "🏋" }
      - { icon: "🎸" }

  - name: "Egecan Aktan, BSc"
    image: "/images/egecan-aktan.jpg"
    designation:
    link:
    content: >
       Egecan'ın çalışmaları bozulabilir ürünler için parti büyüklüğü belirleme üzerine yoğunlaşmaktadır. Ayrıca lojistik, çizelgeleme ve kaynak tahsisine yönelik simülasyon, optimizasyon ve yapay zekâ uygulamalarına ilgi durmaktadır. 
       Şu anda aynı bölümden lisans derecesi de aldığı [Özyeğin Üniversitesi](https://www.ozyegin.edu.tr/tr)'nde Endüstri Mühendisliği yüksek lisans eğitimine devam etmektedir.
    hobbies:
      - { icon: "☕", label: "Blanc 1664" }
      - { icon: "🎬", label: "Dune" }
      - { icon: "🎮", label: "Expedition 33" }
      - { icon: "🎵", label: "Dream Theater" }

    hobby_icons:
      - { icon: "🏀" }
      - { icon: "🎲" }
      - { icon: "🃏" }
      - { icon: "🥊" }
      - { icon: "🥁" }
      - { icon: "🎳" }
      - { icon: "🏁" }

    socials:
    - { icon: "ion ion-logo-linkedin", link: "https://www.linkedin.com/in/egecan-aktan-200b88135/" }
    - { icon: "ion ion-logo-github", link: "https://github.com/Egecan33" }

  - name: "Enes Tanrıkulu"
    image: "/images/enes-tanrikulu.jpg"
    designation:
    link:
    content : >
       Enes, optimizasyon ve matematiksel modelleme konularına ilgi duymakta, veri odaklı karar destek sistemlerinin tasarımına katkı sağlamaktadır. Çalışmaları, gerçek endüstri uygulamaları olan büyük ölçekli çizelgeleme problemleri üzerine yoğunlaşmaktadır.
        [Koç Üniversitesi](http://ku.edu.tr/)'nde Endüstri Mühendisliği okurken Bilgisayar Mühendisliği'nde çift anadal programına devam etmektedir.

    hobbies:
      - { icon: "☕", label: "Cortado" }
      - { icon: "🎬", label: "Paths of Glory" }
      - { icon: "🎮", label: "Minecraft" }
      - { icon: "🎵", label: "Blues" }

    hobby_icons:
    - { icon: "🏋" }
    - { icon: "📖" }

    socials:
    - { icon: "ion ion-logo-linkedin", link: "https://www.linkedin.com/in/enes-tanrıkulu-363845145" }
    - { icon: "ion ion-logo-github", link: "https://github.com/enestanrikuluu" }

  - name: "Erhun Kundakcıoğlu, PhD"
    image: "/images/erhun-kundakcioglu.jpg"
    designation:
    link:
    content: >
      Prof. Erhun Kundakcıoğlu, [Sabancı Üniversitesi](https://www.sabanciuniv.edu/)'nde Endüstri Mühendisliği bölümünde öğretim üyesi ve Datart Labortatuvarı'nın direktörüdür. Araştırmaları karar analitiği ve matematiksel optimizasyona odaklanmaktadır. [Florida Üniversitesi](https://www.ufl.edu)'nden Endüstri ve Sistem Mühendisliği alanında doktora derecesi almıştır. Daha önce [Houston Üniversitesi](https://uh.edu) ve [Özyeğin Üniversitesi](https://www.ozyegin.edu.tr)'nde öğretim üyeliği yapmış, ayrıca [Optym](https://optym.com)'de direktör olarak görev almıştır.
    hobbies:
      - { icon: "☕", label: "Espresso" }
      - { icon: "🎬", label: "Shawshank Redemption" }
      - { icon: "🎮", label: "FIFA" }
      - { icon: "🎵", label: "The Milk Carton Kids" }
    hobby_icons:
      - { icon: "🏀" }
      - { icon: "🎸" }
    socials:
        - {icon: "ion ion-logo-linkedin", link: "https://www.linkedin.com/in/erhunkundakcioglu"}
        - {icon: "ion ion-logo-github", link: "https://github.com/OEKundakcioglu"}
        - {icon: "fa-brands fa-google-scholar", link: "https://scholar.google.com/citations?user=k6NTKvsAAAAJ&hl=en"}

  - name: "Esma Nehir Vardar"
    image: "/images/nehir-vardar.jpg"
    designation:
    link:
    content: >
        Nehir, Datart Laboratuvarı'nda yöneylem araştırması üzerine çalışmakta, gerçek hayata uygulanabilir çözümler geliştirirken verinin ve algoritmaların pratik problemlere nasıl uygulandığını öğrenmektedir. [Özyeğin Üniversitesi](https://www.ozyegin.edu.tr/tr)
        Bilgisayar Mühendisliği bölümünde lisans eğitimi alırken, Endüstri Mühendisliği alanında yandal programına devam etmektedir.
    hobbies:
      - { icon: "☕", label: "Soğuk Americano" }
      - { icon: "🎬", label: "Inglourious Basterds" }
      - { icon: "🎵", label: "Queen" }

    hobby_icons:
      - { icon: "🎸" }
      - { icon: "🏐" }
    socials:
        - {icon: "ion ion-logo-linkedin", link: "https://www.linkedin.com/in/esma-nehir-vardar-4448562b5"}
        - {icon: "ion ion-logo-github", link: "https://github.com/nehirvardar"}

  - name: "Muhammed Esad Simitcioğlu, MSc"
    image: "/images/esad-simitcioglu.jpg"
    designation:
    link:
    content: >
     Esad, gizlilik, makine öğrenimi ve yazılım mühendisliği alanlarında uzmanlaşmıştır ve tam donanımlı geliştirme (full-stack) ile sistem entegrasyonu konularında güçlü bir yetkinliğe sahiptir. 
     Datart Laboratuvarı'nda lead developer olarak görev yapmakta ve optimizasyon motorları ile karar analitiği platformlarına katkı sağlamaktadır. Bilgisayar Bilimleri alanında yüksek lisans eğitimini [Koç Üniversitesi](http://ku.edu.tr/)'nde tamamlamıştır.

    hobbies:
      - { icon: "☕", label: "Çay" }
      - { icon: "🎮", label: "Baldur's Gate" }
    hobby_icons:
      - { icon: "🎾" }  
      - { icon: "💻" }

    socials:
    - { icon: "ion ion-logo-linkedin", link: "https://www.linkedin.com/in/muhammed-esad-simitcioglu" }
    - { icon: "ion ion-logo-github", link: "https://github.com/EsadSimitcioglu" }
    - { icon: "fa-brands fa-google-scholar", link: "https://scholar.google.com/citations?user=dLcZwYsAAAAJ" }


  - name: "Nurullah Y. Duru, BSc"
    image: "/images/nurullah-duru.jpg"
    designation:
    link:
    content: >
     Nurullah'ın araştırmaları, bozulabilir gıda tedarik zincirleri üzerine odaklanmaktadır. Ayrıca makine öğrenimi ve optimizasyon algoritmalarının entegrasyonuna ilgi duymaktadır. Spor analitiğine de ilgisi olan Nurullah basketbol ve futbol karşılaşmaları için veriye dayalı analizler yapmaktadır. Lisans derecesini de aynı bölümden aldığı [Özyeğin Üniversitesi](https://www.ozyegin.edu.tr/tr)'nde Endüstri Mühendisliği yüksek lisans eğitimine devam etmektedir.

    hobbies:
      - { icon: "☕", label: "Çay" }
      - { icon: "🎬", label: "Seven" }
      - { icon: "🎮", label: "NBA 2K" }
      - { icon: "🎵", label: "Kendrick Lamar" }

    hobby_icons:
      - { icon: "🏀" }
      - { icon: "⚽" }
    
    socials:
    - { icon: "ion ion-logo-linkedin", link: "https://www.linkedin.com/in/nurullah-yusuf-duru-81253a16b" }
    - { icon: "ion ion-logo-github", link: "https://github.com/NurullahYusufDuru" }

  - name: "Ulvi Fındık, MSc"
    image: "/images/ulvi-findik.jpeg"
    designation:
    link:
    content: >
     Ulvi'nin çalışmaları endüstriyel optimizasyon, karar analitiği ve uygulamalı yöneylem araştırması üzerinedir. Farklı alanlarda gelişmiş çizelgeleme ve optimizasyon çözümleri geliştirme konusunda uygulamalı deneyime sahiptir. [Özyeğin Üniversitesi](https://www.ozyegin.edu.tr/tr)'nden Endüstri Mühendisliği alanında lisans ve yüksek lisans derecelerini almış, [Sabancı Üniversitesi](https://www.sabanciuniv.edu/tr) Endüstri Mühendisliği bölümünde doktora eğitimine devam etmektedir.

    hobbies:
      - { icon: "☕", label: "Filtre Kahve" }
      - { icon: "🎬", label: "The Prestige" }
      - { icon: "🎮", label: "Dota 2" }
      - { icon: "🎵", label: "Daft Punk, Muse" }

    hobby_icons:
      - { icon: "🏋" }
      - { icon: "🎮" }
      
    socials:
      - { icon: "ion ion-logo-linkedin", link: "https://www.linkedin.com/in/ulvi-fındık" }
      - { icon: "ion ion-logo-github", link: "https://github.com/ulvifk" }


#-------------------------------
# Blog Section
blog:
  enable: false

blog__settings:
  blog__title:
  blog__description:


#-------------------------------
# Footer Settings
footer__background__image:


#-------------------------------
# Contact Settings
İletişim:
  email: # Add your form_id
  description: # Add a description of your form

# NOTE
# Akio theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: false
  disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics:
# Add your GA Tracking Id
