#-------------------------------
# Site Settings
title: Datart Lab
logo: /images/logo_trimmed.png # You can add own logo. For example '/images/logo.png'.
description: Site description
color_scheme: light # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Work'
      url: '/work/'
    - title: 'Team'
      url: '/team/'
    - title: 'Contact'
      url: '/contact/'


#-------------------------------
# Author Settings
author:
  author__name: Author Name
  author__bio: Author Bio
  author__avatar:

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title:
  hero__description:
  hero__image: /images/hero.jpg


#-------------------------------
# Logos Settings
logos:
  enable: true
  logos__title: Industry Collaborators

logo__items:

  - name: Arute
    link: "http://arutesolutions.com/"
    image: "/images/arute.png"

  - name: Bicakcilar
    link: "https://kocmedical.com/"
    image: "/images/bicakcilar.svg"

  - name: Borcelik
    link: "https://www.borcelik.com/"
    image: "/images/borcelik.png"

  - name: Cansan
    link: "https://www.cansan.com.tr/"
    image: "/images/cansan.png"

  - name: Durak
    link: "https://durak.com/"
    image: "/images/durak.png"

  - name: Funthemental
    link: "http://www.funthemental.com.tr/"
    image: "/images/fm.png"

  - name: Harris Health
    link: "https://www.harrishealth.org/"
    image: "/images/hh.png"

  - name: Hitit
    link: "https://www.hitit.com/"
    image: "/images/hitit.png"

  - name: Honeywell
    link: "https://www.honeywell.com/"
    image: "/images/hw.png"

  - name: Keller Williams
    link: "https://www.kw.com/"
    image: "/images/kw.png"

  - name: Kronos
    link: "https://www.ukg.com/"
    image: "/images/ukg.png"

  - name: Magic Generations
    link: "https://www.mgsportif.com/"
    image: "/images/mg.png"

  - name: Mir Unique Solutions
    link: "https://www.mirarge.com/"
    image: "/images/mir.png"

  - name: Modular Mining
    link: "https://www.komatsu.com/"
    image: "/images/Komatsu.png"

  - name: Tam Finans
    link: "https://www.tamfinans.com.tr/"
    image: "/images/tamfinans.png"

  - name: Turkuvaz Medya Grubu
    link: "https://www.turkuvazmedyagrubu.com.tr/"
    image: "/images/tmg.png"




#-------------------------------
# Newsletter
mailchimp:
  enable: false
  mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__input__text: Your email address...
  mailchimp__button__text: Subscribe


#-------------------------------
# Work Settings
work:
  enable: true
  work__title: Work title
  work__description: Work description


#-------------------------------
# Testimonials Section
testimonials:
  enable: true

testimonial__title:
testimonial__description:

testimonial__items:

  - name: "Ahmet Mert Yazıcı"
    image: "/images/mert-yazici.jpg"
    designation:
    link:
    content: >
     Ahmet Mert Yazıcı, Datart Lab’de ölçeklenebilir uygulamalar, backend servisleri ve veri odaklı çözümler tasarlayıp geliştirmeye odaklanmaktadır.
     Koç Üniversitesi’nde Bilgisayar Mühendisliği lisans eğitiminin yanı sıra İşletme çift anadal programını sürdürmektedir.
    socials:
      - { icon: "ion ion-logo-linkedin", link: "https://www.linkedin.com/in/ahmet-mert-yazici" }
      - { icon: "ion ion-logo-github", link: "https://github.com/ayazici21" }


  - name: "Egecan Aktan, BSc"
    image: "/images/egecan-aktan.jpg"
    designation:
    link:
    content: >
      Egecan Aktan earned his BSc degree in Industrial Engineering at Özyeğin University, where he is currently pursuing his MSc in the same field.


  - name: "Enes Tanrıkulu"
    image: "/images/enes-tanrikulu.jpg"
    designation:
    link:
    content : >
      Enes Tanrıkulu, Datart Lab’de ölçeklenebilir uygulamalar, yüksek performanslı optimizasyon modelleri ve kurumsal problemlere yönelik veri odaklı çözümler geliştirmeye odaklanmaktadır.
       Koç Üniversitesi’nde Endüstri Mühendisliği lisans programında, Makine Öğrenmesi odaklı bir hattı takip ederek son sınıf öğrencisi olarak öğrenim görmekte ve aynı zamanda
        Bilgisayar Mühendisliği çift anadal programını sürdürmektedir.
    socials:
    - { icon: "ion ion-logo-linkedin", link: "https://www.linkedin.com/in/enes-tanrıkulu-363845145" }
    - { icon: "ion ion-logo-github", link: "https://github.com/enestanrikuluu" }

  - name: "Erhun Kundakcıoğlu, PhD"
    image: "/images/erhun-kundakcioglu.jpeg"
    designation:
    link:
    content: >
      Dr. Erhun Kundakcıoğlu, Sabancı Üniversitesi Endüstri Mühendisliği Bölümü’nde profesör olarak görev yapmakta ve Datart Lab’in direktörlüğünü yürütmektedir. Araştırmaları karar analitiği ve matematiksel optimizasyon üzerine yoğunlaşmaktadır. 
      Florida Üniversitesi’nde Endüstri ve Sistem Mühendisliği alanında doktora derecesini almıştır. Daha önce Houston Üniversitesi ve Özyeğin Üniversitesi’nde öğretim üyeliği yapmış, ayrıca Optym’de “Distinguished Scientist” olarak görev almıştır.
       TÜBİTAK’ın Kariyer Geliştirme (CAREER) Ödülü’nü kazanmış olup, optimizasyon alanındaki çeşitli dergilerde editörlük görevini sürdürmektedir.
    socials:
        - {icon: "ion ion-logo-linkedin", link: "https://www.linkedin.com/in/erhunkundakcioglu"}
        - {icon: "ion ion-logo-github", link: "https://github.com/OEKundakcioglu"}
        - {icon: "fa-brands fa-google-scholar", link: "https://scholar.google.com/citations?user=k6NTKvsAAAAJ&hl=en"}

  - name: "Esma Nehir Vardar"
    image: "/images/nehir-vardar.jpg"
    designation:
    link:
    content: >
        Esma Nehir Vardar explores operations research, develops real-life solutions, and learns how data and algorithms are applied to practical problems at Datart Lab. She is currently a junior Computer Science student at Özyeğin University, with a minor in Industrial Engineering.
    socials:
        - {icon: "ion ion-logo-linkedin", link: "https://www.linkedin.com/in/esma-nehir-vardar-4448562b5"}
        - {icon: "ion ion-logo-github", link: "https://github.com/nehirvardar"}

  - name: "Muhammed Esad Simitcioğlu, MSc"
    image: "/images/esad-simitcioglu.jpg"
    designation:
    link:
    content: >
      M. Esad Simitcioğlu, Koç Üniversitesi’nde Bilgisayar Bilimleri yüksek lisansını tamamlamış olup, çalışmalarını Gizlilik, Makine Öğrenmesi ve Yazılım Mühendisliği alanlarında yoğunlaştırmıştır.
       Kodlamanın dışında, uzun süredir bir video oyun tutkunu ve tenis meraklısıdır; 
      ister hata ayıklamak, ister algoritmaları çözmek, isterse kortta topa girmek olsun, her zaman meydan okumaya hazırdır.
    socials:
    - { icon: "ion ion-logo-linkedin", link: "https://www.linkedin.com/in/muhammed-esad-simitcioglu" }
    - { icon: "ion ion-logo-github", link: "https://github.com/EsadSimitcioglu" }
    - { icon: "fa-brands fa-google-scholar", link: "https://scholar.google.com/citations?user=dLcZwYsAAAAJ" }


  - name: "Nurullah Y. Duru, BSc"
    image: "/images/nurullah-duru.jpg"
    designation:
    link:
    content: >
       Nurullah Y. Duru earned his BSc degree in Industrial Engineering at Özyeğin University, where he is currently pursuing his MSc in the same field.

  - name: "Ulvi Fındık, MSc"
    image: "/images/ulvi-findik.jpeg"
    designation:
    link:
    content: >
      Ulvi Fındık, Özyeğin Üniversitesi’nden Endüstri Mühendisliği alanında hem lisans hem de yüksek lisans derecelerine sahiptir.
       Araştırmaları, endüstriyel optimizasyon, karar analitiği ve uygulamalı operasyon araştırmaları üzerine odaklanmakta olup,
        çeşitli uygulama alanlarında gelişmiş planlama ve optimizasyon çözümleri geliştirme konusunda pratik deneyime sahiptir. 
        Sabancı Üniversitesi’nde Endüstri Mühendisliği alanında doktora çalışmalarını sürdürmektedir.
    socials:
      - { icon: "ion ion-logo-linkedin", link: "https://www.linkedin.com/in/ulvi-fındık" }
      - { icon: "ion ion-logo-github", link: "https://github.com/ulvifk" }

#-------------------------------
# Blog Section
blog:
  enable: false

blog__settings:
  blog__title:
  blog__description:


#-------------------------------
# Footer Settings
footer__background__image:

#-------------------------------
# Contact Settings
contact:
  email: # Add your form_id
  description: # Add a description of your form

# NOTE
# Akio theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: false
  disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics:
# Add your GA Tracking Id
